repos:

  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [--strict]
        exclude: noxfile.py
        exclude: setup.py

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort